services:
  - type: web
    name: sewing-app-lab8
    env: docker
    repo: https://github.com/max-x-0/sewing-app
    region: oregon
    plan: free
    autoDeploy: true
    healthCheckPath: /index.php
