name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Завантаження коду
        uses: actions/checkout@v3

      - name: Встановлення PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Перевірка PHP синтаксису
        run: php -l index.php
