name: CI (Build & Test)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Завантаження коду
        uses: actions/checkout@v3

      - name: 2. Встановлення PHP (8.1)
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: 3. Встановлення Composer залежностей
        run: composer install --prefer-dist --no-progress

      - name: 4. Запуск автоматизованих тестів (PHPUnit) 🧪
        run: composer run test
